language: node_js

node_js:
  - "node"

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

script:
  - npm install cypress
  # start server in the background
  - npm start &
  # run all Cypress tests and record on the dashboard
  - npm test
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true
